---
# tasks file for roles/ubuntu/elk/elasticsearch
- name: add elasticsearch apt key
  become: yes
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: add source
  shell: echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-7.x.list

- name: update ubuntu
  become: yes
  apt:
    update_cache: yes

- name: install elasticsearch
  apt:
    name: elasticsearch
    update_cache: yes

- name: update config file
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: 'network.host:'
    line: 'network.host: 127.0.0.1'

- name: update the port config
  lineinfile:
    destfile: /etc/elasticsearch/elasticsearch.yml
    regexp: 'http.port:'
    line: 'http.port: 9200'

- name: start elasticsearch
  become: yes
  shell: systemctl start elasticsearch

- name: enable elasticsearch
  service:
    name: elasticsearch
    enabled: yes
