---
# tasks for ubuntu (FINAL-EXAM)
- name: include config.yaml
  hosts: all
  tasks:
    - name: include the config
      include_vars:
        file: config.yaml

- name: change motd for centos and opensuse hosts
  become: yes
  hosts:
    - centos
    - opensuse
  tasks:
    - name: MOTD changed
      lineinfile:
        path: /etc/motd
        line: Ansible Managed by '{{ user }}'

- name: change motd for ubuntu
  hosts: ubuntu
  tasks:
    - name: MOTD changed
      become: yes
      command: sh -c 'echo "Ansible Managed by {{ user }}" > /etc/motd'

- name: pre-requiste to install in ubuntu
  hosts: ubuntu
  roles:
    - ubuntu/prelimclone
    - ubuntu/installvsftpd
    - ubuntu/configvsftpd
    - ubuntu/installnagios
    - ubuntu/confignagios

- name: pre-requisite to install in centos
  hosts: centos
  roles:
    - centos/prelimclone
    - centos/installvsftpd
    - centos/configvsftpd
    - centos/installnagios
    - centos/confignagios

- name: pre-requisite to install in opensuse
  hosts: opensuse
  roles:
    - opensuse/prelimclone
    - opensuse/installvsftpd
    - opensuse/configvsftpd
    - opensuse/installnagios
    - opensuse/confignagios
